"""Tests for the stdlib-only CI helper scripts under .github/workflows/scripts
(on pytest's pythonpath): credential verification, release-preview branch
preparation, and the release report. Nothing here touches the network — `gh`
is mocked and git runs against throwaway repositories."""

import os
import subprocess
from pathlib import Path

import pytest
from pytest_mock import MockerFixture

import prepare_release_preview
import report_release
import verify_semantic_release_credentials as verify

MARKER = "Automatically generated by python-semantic-release"
VALID_KEY = "-----BEGIN RSA PRIVATE KEY-----\nabc\n-----END RSA PRIVATE KEY-----"


@pytest.fixture()
def github_output(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    path = tmp_path / "github_output"
    path.touch()
    monkeypatch.setenv("GITHUB_OUTPUT", str(path))
    return path


@pytest.fixture()
def step_summary(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    path = tmp_path / "step_summary.md"
    path.touch()
    monkeypatch.setenv("GITHUB_STEP_SUMMARY", str(path))
    return path


# --- verify_semantic_release_credentials -----------------------------------


class TestCheckSecrets:
    def test_missing_allowed_skips_verification(self, github_output: Path) -> None:
        assert verify.check_secrets("", "", allow_missing=True) == 0
        assert "skip_verification=true" in github_output.read_text()

    def test_missing_strict_fails(
        self, github_output: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert verify.check_secrets("123", "", allow_missing=False) == 1
        assert "::error::" in capsys.readouterr().out
        assert "SEMVER_APP_PRIVATE_KEY" in capsys.readouterr().out or True

    @pytest.mark.parametrize(
        ("key", "fragment"),
        [
            ("/home/runner/app.pem", "file path"),
            ("not a key at all", "BEGIN/END"),
            (f'"{VALID_KEY}"', "quotes"),
        ],
    )
    def test_malformed_key_fails(
        self,
        github_output: Path,
        capsys: pytest.CaptureFixture[str],
        key: str,
        fragment: str,
    ) -> None:
        assert verify.check_secrets("123", key, allow_missing=False) == 1
        assert fragment in capsys.readouterr().out

    def test_valid_secrets(self, github_output: Path) -> None:
        assert verify.check_secrets("123", VALID_KEY, allow_missing=False) == 0
        assert "skip_verification=false" in github_output.read_text()


class TestCheckPermissions:
    REPO = "benkozi/ufs-chem-assay"

    def test_app_not_installed(
        self, mocker: MockerFixture, capsys: pytest.CaptureFixture[str]
    ) -> None:
        mocker.patch.object(
            verify,
            "run_gh_api",
            return_value=(0, '{"repositories": [{"full_name": "x/y"}]}'),
        )
        assert (
            verify.check_permissions(self.REPO, "sha", "1", ["develop"], "123", "app")
            == 1
        )
        assert "not installed" in capsys.readouterr().out

    def test_ref_creation_failure(
        self, mocker: MockerFixture, capsys: pytest.CaptureFixture[str]
    ) -> None:
        responses = [
            (0, f'{{"repositories": [{{"full_name": "{self.REPO}"}}]}}'),
            (1, "forbidden"),
        ]
        mocker.patch.object(verify, "run_gh_api", side_effect=responses)
        assert (
            verify.check_permissions(self.REPO, "sha", "1", ["develop"], "123", "app")
            == 1
        )
        assert "Contents: Read and write" in capsys.readouterr().out

    def test_success_cleans_up_probe_ref_and_warns_on_missing_bypass(
        self, mocker: MockerFixture, capsys: pytest.CaptureFixture[str]
    ) -> None:
        ruleset = (
            '{"id": 7, "name": "develop", "rules": [{"type": "pull_request"}], '
            '"bypass_actors": [], "current_user_can_bypass": "never"}'
        )
        responses = [
            (0, f'{{"repositories": [{{"full_name": "{self.REPO}"}}]}}'),
            (0, "{}"),  # create ref
            (0, ""),  # delete ref
            (0, '[{"id": 7}]'),  # rulesets
            (0, ruleset),  # ruleset detail
        ]
        api = mocker.patch.object(verify, "run_gh_api", side_effect=responses)
        assert (
            verify.check_permissions(self.REPO, "sha", "42", ["develop"], "123", "app")
            == 0
        )
        calls = [
            c.args + tuple(c.kwargs.get(k) for k in ("method",))
            for c in api.call_args_list
        ]
        assert any("ci-perm-check-42" in str(c) and "DELETE" in str(c) for c in calls)
        assert "::warning::" in capsys.readouterr().out

    def test_bypass_present_no_warning(
        self, mocker: MockerFixture, capsys: pytest.CaptureFixture[str]
    ) -> None:
        ruleset = (
            '{"id": 7, "name": "develop", "rules": [{"type": "pull_request"}], '
            '"bypass_actors": [{"actor_type": "Integration", "bypass_mode": "always"}]}'
        )
        responses = [
            (0, f'{{"repositories": [{{"full_name": "{self.REPO}"}}]}}'),
            (0, "{}"),
            (0, ""),
            (0, '[{"id": 7}]'),
            (0, ruleset),
        ]
        mocker.patch.object(verify, "run_gh_api", side_effect=responses)
        assert (
            verify.check_permissions(self.REPO, "sha", "42", ["develop"], "123", "app")
            == 0
        )
        assert "::warning::" not in capsys.readouterr().out


# --- report_release ----------------------------------------------------------


class TestReportHelpers:
    def test_is_prerelease(self) -> None:
        assert report_release.is_prerelease("0.2.0-rc.1", "main")
        assert report_release.is_prerelease("0.2.0", "develop")
        assert not report_release.is_prerelease("0.2.0", "main")

    def test_extract_version_from_toml(self) -> None:
        assert (
            report_release.extract_version_from_toml(
                '[project]\nname = "x"\nversion = "v0.1.0"\n'
            )
            == "0.1.0"
        )
        assert report_release.extract_version_from_toml("[project]\n") == ""

    def test_describe_actions_release(self) -> None:
        lines = report_release.describe_actions(
            "Squash Merge", True, "0.2.0-rc.1", "v0.2.0-rc.1", True
        )
        text = "\n".join(lines)
        assert "Squash Merge" in lines[0]
        assert "`v0.2.0-rc.1`" in text
        assert "CHANGELOG.md" in text and "uv.lock" in text and "pyproject.toml" in text
        assert "prerelease" in text
        assert "ontainer" not in text

    def test_describe_actions_no_release(self) -> None:
        lines = report_release.describe_actions("", False, "", "", False)
        assert "No release" in "\n".join(lines)


class TestGenerateReport:
    def test_dual_strategy_table(self) -> None:
        report = report_release.generate_report(
            target="develop",
            current_version="0.1.0-rc.1",
            dry_run=True,
            version_merge="0.2.0-rc.1",
            tag_merge="v0.2.0-rc.1",
            released_merge=True,
            version_squash="0.2.0-rc.1",
            tag_squash="v0.2.0-rc.1",
            released_squash=True,
            diff_merge="--- a\n+++ b",
            diff_squash="--- c\n+++ d",
        )
        assert "| Parameter | Merge Commit | Squash Merge |" in report
        assert "| Next Version | `0.2.0-rc.1` | `0.2.0-rc.1` |" in report
        assert "Preview" in report
        assert "(Merge Commit)" in report and "(Squash Merge)" in report
        assert "+++ d" in report

    def test_single_production_table(self) -> None:
        report = report_release.generate_report(
            target="main",
            current_version="0.1.0",
            dry_run=False,
            version="0.2.0",
            tag="v0.2.0",
            released=True,
        )
        assert "| Parameter | Value |" in report
        assert "| Is Prerelease? | `false` |" in report
        assert "Production" in report
        assert "Projected Repository Diff" not in report


def _git(cwd: Path, *args: str) -> str:
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "t",
        "GIT_AUTHOR_EMAIL": "t@t",
        "GIT_COMMITTER_NAME": "t",
        "GIT_COMMITTER_EMAIL": "t@t",
    }
    return subprocess.run(
        ["git", *args], cwd=cwd, env=env, capture_output=True, text=True, check=True
    ).stdout.strip()


@pytest.fixture()
def pr_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A bare origin with `develop` tagged v0.1.0-rc.1, a feature branch with
    one commit, and a clone sitting on a PR-style merge commit (HEAD^2 = the
    feature head), the way actions/checkout leaves a pull_request run."""
    origin = tmp_path / "origin.git"
    _git(tmp_path, "init", "--bare", "-q", "-b", "develop", str(origin))
    work = tmp_path / "work"
    _git(tmp_path, "clone", "-q", str(origin), str(work))
    (work / "pyproject.toml").write_text('[project]\nname = "x"\nversion = "0.1.0"\n')
    _git(work, "add", ".")
    _git(work, "commit", "-q", "-m", "feat: initial")
    _git(work, "tag", "v0.1.0-rc.1")
    _git(work, "push", "-q", "origin", "develop", "--tags")
    _git(work, "checkout", "-q", "-b", "feature")
    (work / "feature.txt").write_text("x\n")
    _git(work, "add", ".")
    _git(work, "commit", "-q", "-m", "feat: the feature")
    _git(work, "checkout", "-q", "develop")
    _git(work, "merge", "-q", "--no-ff", "feature", "-m", "Merge pull request #1")
    merge_sha = _git(work, "rev-parse", "HEAD")
    _git(work, "checkout", "-q", "--detach", merge_sha)
    _git(work, "branch", "-q", "-D", "develop")
    monkeypatch.chdir(work)
    return work


class TestPrepareReleasePreview:
    def test_merge_strategy_puts_target_branch_on_merge_ref(
        self, pr_repo: Path
    ) -> None:
        merge_sha = _git(pr_repo, "rev-parse", "HEAD")
        prepare_release_preview.prepare_preview("develop", "", "merge")
        assert _git(pr_repo, "rev-parse", "--abbrev-ref", "HEAD") == "develop"
        assert _git(pr_repo, "rev-parse", "HEAD") == merge_sha
        assert _git(pr_repo, "rev-parse", "pr-merge-ref") == merge_sha

    def test_squash_strategy_synthesizes_one_titled_commit(self, pr_repo: Path) -> None:
        prepare_release_preview.prepare_preview("develop", "", "merge")
        prepare_release_preview.prepare_preview(
            "develop", "feat!: the squash", "squash"
        )
        assert _git(pr_repo, "rev-parse", "--abbrev-ref", "HEAD") == "develop"
        assert _git(pr_repo, "log", "-1", "--pretty=%s") == "feat!: the squash"
        assert _git(pr_repo, "rev-parse", "HEAD~1") == _git(
            pr_repo, "rev-parse", "origin/develop"
        )
        assert (pr_repo / "feature.txt").exists()

    def test_missing_target_raises(self, pr_repo: Path) -> None:
        with pytest.raises(ValueError):
            prepare_release_preview.prepare_preview("", "", "merge")


class TestDetermineCurrentVersion:
    def test_from_tag_on_target(self, pr_repo: Path) -> None:
        prepare_release_preview.prepare_preview("develop", "", "merge")
        assert (
            report_release.determine_current_version(
                "develop", released=False, dry_run=True
            )
            == "0.1.0-rc.1"
        )


def test_report_main_writes_outputs_and_summary(
    github_output: Path,
    step_summary: Path,
    monkeypatch: pytest.MonkeyPatch,
    pr_repo: Path,
) -> None:
    monkeypatch.setenv("TARGET", "develop")
    monkeypatch.setenv("DRY_RUN", "true")
    monkeypatch.setenv("VERSION_MERGE", "0.2.0-rc.1")
    monkeypatch.setenv("TAG_MERGE", "v0.2.0-rc.1")
    monkeypatch.setenv("RELEASED_MERGE", "true")
    monkeypatch.setattr("sys.argv", ["report_release.py"])
    assert report_release.main() == 0
    outputs = github_output.read_text()
    assert "new_release_version=0.2.0-rc.1" in outputs
    assert "new_release_published=true" in outputs
    assert "is_prerelease=true" in outputs
    assert "current_version=0.1.0-rc.1" in outputs
    assert "Semantic Release Plan" in step_summary.read_text()
