"""Session-end spatial plots and GIFs per combination.

Mirrors the plotting portions of cece-data-viewer/app/analysis.py (PlateCarree
maps, viridis pcolormesh, coastlines/borders with graceful degradation, tick
formatters instead of draw_labels). The per-variable color scale is derived
from the descriptive statistics — exact suite-wide min/max, never percentiles:
this is an evaluation tool, and an outlier that washes out a plot is itself a
finding.
"""

from __future__ import annotations

import datetime
import warnings
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import cartopy.crs as ccrs  # noqa: E402
import cartopy.feature as cfeature  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import xarray as xr  # noqa: E402
from cartopy.mpl.ticker import LatitudeFormatter, LongitudeFormatter  # noqa: E402
from PIL import Image  # noqa: E402
from pydantic import BaseModel, ConfigDict  # noqa: E402

from analysis import _file_time  # noqa: E402
from logs import HARNESS_NAME, get_logger  # noqa: E402

logger = get_logger("plotting")

PLOTS_DIRNAME = "plots-overview"
BIAS_PLOTS_DIRNAME = "plots-baselines"
_FRAME_DURATION_MS = 400
_FOOTER = f"Generated by {HARNESS_NAME} {{timestamp}}"


class VariableScale(BaseModel):
    """Suite-wide color scale for one variable: the exact data range."""

    model_config = ConfigDict(frozen=True)

    variable: str
    vmin: float
    vmax: float


def derive_scales(stats: pd.DataFrame) -> dict[str, VariableScale]:
    """Per-variable scales from the concatenated descriptive stats: exact
    min(min)/max(max) across all files and combos. No NetCDF is re-read."""
    scales: dict[str, VariableScale] = {}
    for variable, group in stats.groupby("variable"):
        vmin = float(group["min"].min())
        vmax = float(group["max"].max())
        if (
            vmin == vmax
        ):  # degenerate (e.g. all-zero field): give matplotlib a valid range
            vmin, vmax = vmin - 0.5, vmax + 0.5
        scales[str(variable)] = VariableScale(
            variable=str(variable), vmin=vmin, vmax=vmax
        )
        logger.info("color scale for %s: [%.6g, %.6g]", variable, vmin, vmax)
    return scales


def _units_label(da: xr.DataArray) -> str:
    units = str(da.attrs.get("units", "")).strip()
    return f"[{units}]" if units else "[unknown]"


def render_spatial_plot(
    nc_path: Path, variable: str, scale: VariableScale, out_path: Path
) -> None:
    """One PNG for one (file, variable): first timestep/level when present."""
    with xr.open_dataset(nc_path, engine="netcdf4") as ds:
        da = ds[variable]
        time_label = ""
        file_time = _file_time(ds)
        if file_time is not None:
            time_label = file_time.isoformat()
        if "time" in da.dims:
            da = da.isel(time=0)
        if "lev" in da.dims:
            da = da.isel(lev=0)

        lats = da["lat"].values.astype(float)
        lons = da["lon"].values.astype(float)
        data = da.values.astype(float)
        units = _units_label(da)

    fig = plt.figure(figsize=(10, 5))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
    ax.set_global()
    mesh = ax.pcolormesh(
        lons,
        lats,
        data,
        transform=ccrs.PlateCarree(),
        cmap="viridis",
        vmin=scale.vmin,
        vmax=scale.vmax,
    )
    # Geographic boundaries degrade gracefully: cartopy fetches Natural Earth
    # data on first use, and an offline machine still gets a data-only map.
    try:
        ax.coastlines(linewidth=0.6)
    except Exception:
        logger.warning(
            "could not draw coastlines (Natural Earth download may have failed)"
        )
    try:
        ax.add_feature(cfeature.BORDERS, linewidth=0.4, edgecolor="#555555")
    except Exception:
        logger.warning("could not draw BORDERS feature (download may have failed)")
    # Ticker formatters instead of draw_labels=True (cartopy/shapely 2.x issue).
    ax.set_xticks(range(-180, 181, 60), crs=ccrs.PlateCarree())
    ax.set_yticks(range(-90, 91, 30), crs=ccrs.PlateCarree())
    ax.xaxis.set_major_formatter(LongitudeFormatter())
    ax.yaxis.set_major_formatter(LatitudeFormatter())
    ax.gridlines(draw_labels=False, linewidth=0.3, color="#aaaaaa", linestyle="--")

    fig.colorbar(mesh, ax=ax, label=f"{variable} {units}", fraction=0.03, pad=0.04)
    ax.set_title(f"{variable}  {time_label}".rstrip())
    generated = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    fig.text(
        0.99,
        0.01,
        _FOOTER.format(timestamp=generated),
        ha="right",
        va="bottom",
        fontsize=7,
        color="#aaaaaa",
        transform=fig.transFigure,
    )
    fig.tight_layout()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fig.savefig(out_path, format="png", dpi=120)
    plt.close(fig)
    logger.info("wrote %s", out_path)


def render_gif(png_paths: list[Path], out_path: Path) -> None:
    """Assemble PNGs (already in timestamp order) into an animated GIF."""
    frames = [
        Image.open(path)
        .convert("RGB")
        .convert("P", palette=Image.Palette.ADAPTIVE, colors=256)
        for path in png_paths
    ]
    frames[0].save(
        out_path,
        format="GIF",
        save_all=True,
        append_images=frames[1:],
        loop=0,
        duration=_FRAME_DURATION_MS,
    )
    logger.info("wrote %s (%s frame(s))", out_path, len(frames))


def render_combo_plots(
    combo_dir: Path, scales: dict[str, VariableScale], gif_enabled: bool
) -> None:
    """All plots (and per-variable GIFs) for one combination directory."""
    nc_files = sorted(combo_dir.glob("*.nc"))
    if not nc_files:
        return
    plots_dir = combo_dir / PLOTS_DIRNAME
    plots_dir.mkdir(exist_ok=True)

    pngs_by_variable: dict[str, list[Path]] = {}
    for nc_path in nc_files:
        with xr.open_dataset(nc_path, engine="netcdf4") as ds:
            variables = [str(name) for name in ds.data_vars]
        for variable in variables:
            scale = scales.get(variable)
            if scale is None:
                logger.warning(
                    "no scale for variable %s in %s; skipping plot",
                    variable,
                    nc_path.name,
                )
                continue
            out_path = plots_dir / f"{variable}__{nc_path.stem}.png"
            try:
                render_spatial_plot(nc_path, variable, scale, out_path)
            except Exception:
                logger.exception("failed to render %s", out_path)
                continue
            pngs_by_variable.setdefault(variable, []).append(out_path)

    if gif_enabled:
        for variable, png_paths in pngs_by_variable.items():
            try:
                render_gif(png_paths, plots_dir / f"{variable}.gif")
            except Exception:
                logger.exception(
                    "failed to render gif for %s in %s", variable, plots_dir
                )


def render_all_plots(output_root: Path, stats: pd.DataFrame, gif_enabled: bool) -> None:
    """Session-end entry point: derive suite-wide scales from the stats and
    render plots for every combination the stats cover. Combo directories
    come from the frame's combo_id column — pass a per-suite slice of the
    session stats and only that suite's combos render, on that suite's
    scales (the output root is flat across suites). Failures are logged,
    never raised — plots are diagnostic artifacts, not assertions."""
    scales = derive_scales(stats)
    for combo_id in sorted(stats["combo_id"].unique()):
        combo_dir = output_root / str(combo_id)
        try:
            render_combo_plots(combo_dir, scales, gif_enabled=gif_enabled)
        except Exception:
            logger.exception("failed to render plots for %s", combo_dir)


def derive_bias_scales(comparison_stats: pd.DataFrame) -> dict[str, VariableScale]:
    """Per-variable bias color scales from the concatenated comparison stats:
    symmetric about zero at the exact suite-wide max |difference| — never
    percentile-clipped. Guarded for the all-zero-bias case."""
    scales: dict[str, VariableScale] = {}
    for variable, group in comparison_stats.groupby("variable"):
        vmax = float(group["max_abs_diff"].max())
        if not np.isfinite(vmax) or vmax == 0.0:
            vmax = 0.5  # flat bias (e.g. bit-for-bit identical) still renders
        scales[str(variable)] = VariableScale(
            variable=str(variable), vmin=-vmax, vmax=vmax
        )
        logger.info("bias color scale for %s: [%.6g, %.6g]", variable, -vmax, vmax)
    return scales


def render_bias_plot(
    realization_nc: Path,
    baseline_nc: Path,
    variable: str,
    scale: VariableScale,
    out_path: Path,
) -> None:
    """One bias map (realization - baseline) for one (file, variable)."""
    with (
        xr.open_dataset(realization_nc, engine="netcdf4") as real,
        xr.open_dataset(baseline_nc, engine="netcdf4") as base,
    ):
        real_da = real[variable]
        base_da = base[variable]
        time_label = ""
        file_time = _file_time(real)
        if file_time is not None:
            time_label = file_time.isoformat()
        for da_name in ("time", "lev"):
            if da_name in real_da.dims:
                real_da = real_da.isel({da_name: 0})
            if da_name in base_da.dims:
                base_da = base_da.isel({da_name: 0})

        lats = real_da["lat"].values.astype(float)
        lons = real_da["lon"].values.astype(float)
        data = real_da.values.astype(float) - base_da.values.astype(float)
        units = _units_label(real_da)

    fig = plt.figure(figsize=(10, 5))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
    ax.set_global()
    mesh = ax.pcolormesh(
        lons,
        lats,
        data,
        transform=ccrs.PlateCarree(),
        cmap="RdBu_r",
        vmin=scale.vmin,
        vmax=scale.vmax,
    )
    try:
        ax.coastlines(linewidth=0.6)
    except Exception:
        logger.warning(
            "could not draw coastlines (Natural Earth download may have failed)"
        )
    try:
        ax.add_feature(cfeature.BORDERS, linewidth=0.4, edgecolor="#555555")
    except Exception:
        logger.warning("could not draw BORDERS feature (download may have failed)")
    ax.set_xticks(range(-180, 181, 60), crs=ccrs.PlateCarree())
    ax.set_yticks(range(-90, 91, 30), crs=ccrs.PlateCarree())
    ax.xaxis.set_major_formatter(LongitudeFormatter())
    ax.yaxis.set_major_formatter(LatitudeFormatter())
    ax.gridlines(draw_labels=False, linewidth=0.3, color="#aaaaaa", linestyle="--")

    fig.colorbar(mesh, ax=ax, label=f"{variable} bias {units}", fraction=0.03, pad=0.04)
    ax.set_title(f"{variable} bias (realization - baseline)  {time_label}".rstrip())
    generated = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    fig.text(
        0.99,
        0.01,
        _FOOTER.format(timestamp=generated),
        ha="right",
        va="bottom",
        fontsize=7,
        color="#aaaaaa",
        transform=fig.transFigure,
    )
    fig.tight_layout()
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        fig.savefig(out_path, format="png", dpi=120)
    plt.close(fig)
    logger.info("wrote %s", out_path)


def render_combo_bias_plots(
    combo_dir: Path, baseline_dir: Path, scales: dict[str, VariableScale]
) -> None:
    """All bias plots and per-variable GIFs for one compared combination.
    Plots and GIFs are always created together (no separate GIF toggle)."""
    pair_names = sorted(
        {path.name for path in combo_dir.glob("*.nc")}
        & {path.name for path in baseline_dir.glob("*.nc")}
    )
    if not pair_names:
        return
    plots_dir = combo_dir / BIAS_PLOTS_DIRNAME
    plots_dir.mkdir(exist_ok=True)

    pngs_by_variable: dict[str, list[Path]] = {}
    for name in pair_names:
        with xr.open_dataset(combo_dir / name, engine="netcdf4") as ds:
            variables = [str(v) for v in ds.data_vars]
        for variable in variables:
            scale = scales.get(variable)
            if scale is None:
                logger.warning(
                    "no bias scale for variable %s in %s; skipping", variable, name
                )
                continue
            out_path = plots_dir / f"{variable}__{Path(name).stem}.png"
            try:
                render_bias_plot(
                    combo_dir / name, baseline_dir / name, variable, scale, out_path
                )
            except Exception:
                logger.exception("failed to render %s", out_path)
                continue
            pngs_by_variable.setdefault(variable, []).append(out_path)

    for variable, png_paths in pngs_by_variable.items():
        try:
            render_gif(png_paths, plots_dir / f"{variable}.gif")
        except Exception:
            logger.exception(
                "failed to render bias gif for %s in %s", variable, plots_dir
            )


def render_all_bias_plots(
    pairs: list[tuple[Path, Path]], comparison_stats: pd.DataFrame
) -> None:
    """Session-end entry point for bias plotting: one (combo_dir,
    baseline_dir) pair per plot-enabled comparison. Failures are logged,
    never raised."""
    scales = derive_bias_scales(comparison_stats)
    for combo_dir, baseline_dir in pairs:
        try:
            render_combo_bias_plots(combo_dir, baseline_dir, scales)
        except Exception:
            logger.exception("failed to render bias plots for %s", combo_dir)
